### ISSUE TITLE
Does Lyra support publisher side recovery ? 

### ISSUE THREAD

**Issue by yperry** [jhalterman/lyra#32]
Does Lyra support publisher side recovery ? 
What about data loss when publisher side connection fails ? 

I can't see any reference in the code. 
If so, Can someone refer me ?

BTW: 
With the new factory.setAutomaticRecoveryEnabled feature in the rabbitmq java client, is there still a reason to use Lyra at the client side? 
Thanks.

**Comment by jberryman** [comment]
I think it would be super helpful if you could document the differences between `amqp-client`'s recovery capabilities and lyra, and why or whether we should prefer one over the other, and how amqp-client should be configured.

**Comment by jhalterman** [comment]
@jberryman Sure, I can do that.

The short of it is that amqp-client's recovery capabilities are more limited than Lyra's. While Lyra's goal has always been to recover from any kind of failure that could reasonably occur and be recovered from (described here https://github.com/jhalterman/lyra/wiki/Failure-Scenarios), amqp-client only recovers from connection errors, not channel or consumer errors. As for which specific errors it recovers from versus Lyra - I'd need to spend some time seeing where things are at right now.

Aside from recovery, Lyra also supports automatic retries via the same API, events, etc.

**Comment by michaelklishin** [comment]
Yes, RabbitMQ Java client is intentionally minimalistic and more conservative in what it tries to cover in terms of recovery. We've ported a feature set that has proved itself in other clients. Lyra is more feature rich.
