### ISSUE TITLE
RabbitMQ can block forever in exchangeDeclare during recovery

### ISSUE THREAD

**Issue by spatula75** [jhalterman/lyra#45]
This one is probably a little tricky to reproduce, but I was able to get a stack out with jstack.  It appears that what happened was we had called exchangeDeclare immediately before a recovery happened, or possibly during recovery, but RabbitMQ blocked forever waiting for a reply from the server.

Here's the stack we got out with jstack:

Thread 1652: (state = BLOCKED)
 - java.lang.Object.wait(long) @bci=0 (Interpreted frame)
 - java.lang.Object.wait() @bci=2, line=503 (Compiled frame)
 - com.rabbitmq.utility.BlockingCell.get() @bci=8, line=50 (Compiled frame)
 - com.rabbitmq.utility.BlockingCell.uninterruptibleGet() @bci=1, line=89 (Interpreted frame)
 - com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue() @bci=1, line=33 (Interpreted frame)
 - com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply() @bci=4, line=343 (Interpreted frame)
 - com.rabbitmq.client.impl.AMQChannel.privateRpc(com.rabbitmq.client.Method) @bci=15, line=216 (Interpreted frame)
 - com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(com.rabbitmq.client.Method) @bci=2, line=118 (Interpreted frame)
 - com.rabbitmq.client.impl.ChannelN.exchangeDeclare(java.lang.String, java.lang.String, boolean, boolean, boolean, java.util.Map) @bci=38, line=675 (Interpreted frame)
 - com.rabbitmq.client.impl.ChannelN.exchangeDeclare(java.lang.String, java.lang.String, boolean, boolean, java.util.Map) @bci=9, line=662 (Interpreted frame)
 - com.rabbitmq.client.impl.ChannelN.exchangeDeclare(java.lang.String, java.lang.String, boolean) @bci=6, line=692 (Interpreted frame)
 - com.rabbitmq.client.impl.ChannelN.exchangeDeclare(java.lang.String, java.lang.String, boolean) @bci=4, line=61 (Interpreted frame)
 - sun.reflect.GeneratedMethodAccessor71.invoke(java.lang.Object, java.lang.Object[]) @bci=79 (Interpreted frame)
 - sun.reflect.DelegatingMethodAccessorImpl.invoke(java.lang.Object, java.lang.Object[]) @bci=6, line=43 (Interpreted frame)
 - java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) @bci=57, line=606 (Interpreted frame)
 - net.jodah.lyra.internal.util.Reflection.invoke(java.lang.Object, java.lang.reflect.Method, java.lang.Object[]) @bci=3, line=11 (Interpreted frame)
 - net.jodah.lyra.internal.ChannelHandler$1.call() @bci=396, line=131 (Interpreted frame)
 - net.jodah.lyra.internal.RetryableResource.callWithRetries(java.util.concurrent.Callable, net.jodah.lyra.internal.RecurringPolicy, net.jodah.lyra.internal.RecurringStats, java.util.Set, boolean, boolean) @bci=12, line=51 (Interpreted frame)
 - net.jodah.lyra.internal.ChannelHandler.invoke(java.lang.Object, java.lang.reflect.Method, java.lang.Object[]) @bci=88, line=167 (Interpreted frame)

In our log file, we got a stream of messages like "ChannelHandler - Channel channel-5 on cxn-1 was closed unexpectedly" about 1.7 seconds after we would have called exchangeDeclare, so it would *appear* that it was the exchangeDeclare that happened first, before recovery began.  We see the first instance of a ShutdownSignalException roughly 1.8 seconds later when a different exchangeDeclare call happened.  We do not see an exception on the first exchangeDeclare, however, perhaps because it was already blocking prior to the channels being detected as closing unexpectedly.

It looks like probably what should have happened is the blocking get() should have been interrupted somehow when recovery took place so it could throw an exception and bail.

We're seeing this with RabbitMQ's amqp-client-3.3.1, Lyra 0.5.0, and RabbitMQ 3.3.4.

**Comment by spatula75** [comment]
Looking through the RabbitMQ code, it looks like what's supposed to happen on a Shutdown is any pending RPC calls get a setException called on them, which in turn calls set() with a ValueOrException value containing the ShutdownSignalException.  For whatever reason, one of our threads did not see this done to its outstanding RPC call, though it isn't entirely clear whether it was because of Lyra attempting recovery, or because of some problem with the RMQ client itself.

The complete sequence of events looked like this, in order:

1. We call exchangeDeclare
2. RMQ goes away
3. ChannelHandler complains about channels closing unexpectedly
4. Another exchangeDeclare in progress receives the ShutdownSignalException and fails as expected.  The root cause is a missed heartbeat.
5. Lyra begins recovery
6. Recovery completes

**Comment by jhalterman** [comment]
Two quick questions: 

* What does your `Config` look like?
* What are some good steps to reproduce? Based on your description:
  * Spin up a few threads
  * Have the threads declare an exchange every 1 second
  * Kill the server
  * Ensure that all threads exit (are not blocked)

**Comment by spatula75** [comment]
I should point out that I'm not convinced this isn't my own fault, by the way.  This is one of those things where there are a lot of moving parts-- our own code, Lyra, and RabbitMQ's client-- and it's a bit tricky to tell what the root cause is, especially since we've got multiple threads flinging things around.

I did observe in researching further last night that we have a few cases where one Channel might be accessed from multiple threads, which I understand is a no-no with the RabbitMQ client because of the way it does RPC callbacks.  By my reading, the only safe things to do from another thread are async operations that are handled by RMQ (ie, letting your consumer consume).  Declaring an exchange is definitely not a threadsafe operation on a Channel, nor is the publishing of messages, by my reading.

The advice I saw from poking around was that if you must have multiple threads using the same Channel, do it in a synchronized block, synchronizing on the channel object.  I'll be revising some of our code to do that to ensure we're using Channels in a threadsafe fashion.

It might make a decent test case for Lyra of course, if nothing else but to rule out that there's any problem with recovery interfering with the delivery of the ShutdownSignalException to the pending channel RPC.  I think your proposed test case is probably a good one.  It might be good to have more than one channel with many threads on each channel, and kill the server in such a way that at least one of the declareExchange() calls will be stuck waiting on a heartbeat, maybe by making the network connection time out.  I'll be trying some similar failure testing of my own of this type today, too.

Our Config looks like this:

        final Config config = new Config()
                .withRecoveryPolicy(
                        new RecoveryPolicy().withMaxAttempts(250).withBackoff(Duration.seconds(1), Duration.seconds(16)))
                .withRetryPolicy(
                        new RetryPolicy().withMaxAttempts(250).withBackoff(Duration.seconds(1), Duration.seconds(16)));

We also register some listeners that just log, and we register retryable & recoverable exceptions for UnknownHostException, SocketTimeoutException, EOFException, SocketException, ConnectException, NoRouteToHostException, and PortUnreachableException.

Our RMQ options look like this:

            options = new ConnectionOptions().withHost(amqpHost).withRequestedHeartbeat(Duration.seconds(15))
                    .withSocketFactory(new AmqpSocketFactory()).withConnectionTimeout(Duration.seconds(10)).withPort(amqpPort);

**Comment by jhalterman** [comment]
According to the docs, Channel *should* be threadsafe. For my test case, I'm just killing the server (rabbitmqctl stop_app). I'll post my test code shortly...

**Comment by spatula75** [comment]
Yeah, I'm seeing highly contradictory information about that.  The API guide claims Channels are thread-safe, but multiple times on RMQ mailing lists and such, they say they're not thread-safe... the information about thread safety is completely contradictory.  I wonder if they introduced thread-safe channels somewhere along the line, such that older clients maybe aren't, but newer ones are?  Either way, it's frustrating that there are two different answers from the RMQ folks depending on where you look, and they can't both be true.

**Comment by jhalterman** [comment]
Here's my primitive test case so far. I'm not able to reproduce the problem just yet with this. Let me know how you think this can be tweaked:

```
    final Config config = new Config().withRecoveryPolicy(
      new RecoveryPolicy().withMaxAttempts(250).withBackoff(Duration.seconds(1), Duration.seconds(16)))
      .withRetryPolicy(new RetryPolicy().withMaxAttempts(250).withBackoff(Duration.seconds(1), Duration.seconds(16)));
    final ConnectionOptions connectionOptions = new ConnectionOptions().withHost(hostName);
    final ConfigurableConnection connection = Connections.create(connectionOptions, config);

    try {
      final Random random = new Random(System.currentTimeMillis());

      // 5 channels
      for (int i = 0; i < 5; i++) {
        final Channel channel = connection.createChannel();

        // 3 threads per channel
        for (int j = 0; j < 3; j++) {
          new Thread(new Runnable() {
            public void run() {
              while (true) {
                try {
                  Thread.sleep(random.nextInt(500));
                  channel.exchangeDeclare("foo", "direct", false, true, null);
                } catch (Exception e) {
                  e.printStackTrace();
                }
              }
            }
          });
        }
      }

      Thread.sleep(Integer.MAX_VALUE);
```

**Comment by spatula75** [comment]
For example, see this email thread, from late last year: 

http://comments.gmane.org/gmane.comp.networking.rabbitmq.general/33143

At the very bottom of that one:

>"They won't make channel instances safe to share. You *will* run into
concurrency hazards if you publish messages concurrently on a shared
channel, for example.

>I suggest that you synchronize the exchange.declare calls manually
using channel itself as the lock object (if memory footprint is such a major concern)."

And yet, from here: https://www.rabbitmq.com/api-guide.html#channel-threads
We see this:

>"Channel instances are safe for use by multiple threads. Requests into a Channel are serialized, with only one thread being able to run a command on the Channel at a time. Even so, applications should prefer using a Channel per thread instead of sharing the same Channel across multiple threads."

Anyway, it's not your fault of course, but it makes one go ¯\\\_(ツ)\_/¯

**Comment by jhalterman** [comment]
Nice - I may have reproduced it:

![screen shot 2015-02-18 at 10 50 38 am](https://cloud.githubusercontent.com/assets/228804/6254249/0b79a0ea-b75c-11e4-8690-5b1e3070f7de.png)

Does that look like it?

**Comment by jhalterman** [comment]
That comment from @michaelklishin does seem to contradict the docs - but if anyone would know about the thread safety of Channels it would be Michael.

**Comment by spatula75** [comment]
The only thing I can suggest for the test is finding some way for the server to go away via a missed heartbeat rather than killing the server, and see if that behavior is any different.  That was how ours failed on this occasion.  It probably would require some iptables/ipfw/firewall trickery to cause the RMQ server to go unreachable and have the heartbeat check fail, rather than quickly disconnecting.

**Comment by spatula75** [comment]
Your stack from your test does closely resemble the one we got.  Sorry my replies are out of sequence.

**Comment by jhalterman** [comment]
So I'm actually not able to reproduce this yet. I can force the `SocketException` pretty easily by doing rapid `exchangeDeclare` calls, but nothing gets stuck in a blocking state for me. That thread in the screenshot above just happened to be paused when it was on that call. It unblocked afterwords...

**Comment by spatula75** [comment]
Which version of the RabbitMQ Java client are you using?  It's not implausible that there have been some fixes over time that I didn't have from the version we had, too.

**Comment by jhalterman** [comment]
This is with amqp-client 3.3.5 and rabbitmq server 3.4.1.

**Comment by michaelklishin** [comment]
There are two types of operations: those that await responses ("synchronous methods") and those that don't. Synchronous methods are serialised. Asynchronous methods aren't. But synchronisation itself is not a cure for every possible concurrency hazard.

Here are some situations where synchronisation is part of the hazard:

 * You send a synchronous method, connection goes down, reply never arrives.
 * You try to use `Socket#write`, connection goes down mid-write, `Socket#write` never returns (known JDK bug/feature that existed for years)

(the first item is I believe what's going on for @spatula75).

Other known issues (and why the docs that claim that channels are safe to share between threads are wrong/incomplete and should be re-written):

 * You publish concurrently. A published method is at least 2 (typically 3 or more) frames on the wire. You get incorrect interleaving, RabbitMQ treats that as a fatal connection exception.

In all of the above cases, "you are eaten by a grue". Please do not share channels between threads, period. Synchronising publishes would have a significant effect on throughput and makes no sense conceptually.

As for the blocking socket, the only way around this is switching to NIO, which we'll have to do but it's not a particularly high priority for our team of 3.

Summary: don't share channels between threads. Don't expect Lyra, RabbitMQ Java client or any other library to magically make channels entirely safe to share between threads.

**Comment by spatula75** [comment]
Thanks for the response @michaelklishin.  Assuming we are seeing the former case, which I agree sounds probable, how can we cope with that?  Or is that only a problem in the case where a Channel is visible to multiple threads?

In our case, we're injecting a Channel to an @Service using Spring inside a REST web service running inside a servlet container, in which we also have multiple repeating tasks, all of which of course could be executing in different threads.

We could of course serialize requests at the entry points into the @Service to ensure that they're all handled by a single thread, but that sounds like it's the functional equivalent of throwing a serialized(channel) {} block around things really.

Would it be better to create a Channel on the fly each time we intend to execute a synchronous method, and also create a separate Channel for handling the asynchronous stuff (consumption, etc), rather than injecting?

**Comment by jhalterman** [comment]
Thanks @michaelklishin.

@spatula75 - try separate channels for your threads and see if the issue persists.

**Comment by spatula75** [comment]
@jhalterman Will do.  It's going to take a bit of fiddling to get it to happen, but I will try that and advise.  It's starting to sound very much like this is not a Lyra issue, just that Lyra got caught in the crossfire.

**Comment by michaelklishin** [comment]
@spatula75 when a shutdown happens (e.g. there's an exception on the network I/O thread, in `MainLoop`), it is propagated to `ChannelManager` which in turn propagates it to every channel, which sets the last outstanding request's `BlockingValueOrException` to an exception. That should simply throw that exception.

The problem is, we only do that for the last oustanding continuation (request) so when you share a channel, I suspect that there's more than one that needs unblocking.

**Comment by michaelklishin** [comment]
Creating channels on the fly is OK, just remember to close them (as there's a cap on how many you can have and they also consume some server resources) and that it is a network round-trip.

**Comment by spatula75** [comment]
@michaelklishin It looks like in our arrangement, where Spring is injecting our Channel for us, we can use our fancy ThreadScope for the sync calls, but because we need to close channels when threads go away, I believe that won't be okay for consumers waiting for callbacks; for those, it seems like we'd need an instance-scoped Channel (like we had been doing for declaring exchanges, binding queues, publishing messages, etc) which doesn't get closed, since closing the channel would surely kill off our consumers.

The big question now is this: is channel.basicConsume safe to call from multiple threads on that instance-scoped channel, or had I better synchronize around that call?

**Comment by jhalterman** [comment]
It sounds like concurrent `basicConsume` calls could be problematic which is why you ideally want a channel per thread. Something like a thread scope sounds like it could work for this (though I'm not too familiar with Spring).

**Comment by spatula75** [comment]
ThreadScope is _almost_ right I think.  The hard part is knowing when to call channel.close() when running inside a servlet container, and when you might still have some leftover consumers doing work.  I assume if something closes the channel while there are still consumers, bad things will happen.  But we would also want to close unused channels when we really were done with them.  I need to think about it some more and look carefully at when threads are being created and destroyed.

**Comment by michaelklishin** [comment]
@spatula75 `basic.consume` is a synchronous protocol method. You should synchronise its invocations.

Have you considered using shutdown listeners? Shutting down when consumers are really ready to do so is harder but if you abuse a shutdown listener to block and take care of that, it may work.

**Comment by michaelklishin** [comment]
Of course, having idempotent consumers is the best way: then you can shut them down abruptly, messages will be re-queued and delivered later.

But we are heading into the `rabbitmq-users` discussions territory that have little to do with the specific issue reported.

**Comment by spatula75** [comment]
Agreed.  @jhalterman, I think the preponderance of the evidence suggests I have more work to do and that this is more likely caused by improper sharing of Channels across threads than anything Lyra could do to recover from that nicely.  I don't want to abuse your issue space with a tangential discussion, even if it's an interesting one, and if I need more help, I'll pop over to rabbitmq-users. 

Appreciate all the help and advice from you both!
