### ISSUE TITLE
How to implement automatic fail-over to running node

### ISSUE THREAD

**Issue by marcuslinke** [jhalterman/lyra#49]
I really appreciate this library but I wonder if and how it might be possible to implement an automatic fail-over of a producer to a running node given a two nodes rabbitmq cluster where it should be possible to reboot each node without  data loss. Any pointers are welcome. Thanks!

**Comment by jhalterman** [comment]
I'm not sure that this sort of thing can be featurized into a library like Lyra. I'd recommend asking this question on the [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users) list. Perhaps someone there has already done this or has some good alternative solutions.
