### ISSUE TITLE
Documentation on ConnectionFactory used in ConnectionOptions

### ISSUE THREAD

**Issue by augi** [jhalterman/lyra#67]
It would be nice to have documented how custom `ConnectionFactory` should be configured when passed to `ConnectionOptions`. Esp. we are not sure if we should call `connectionFactory.setAutomaticRecoveryEnabled(true)`.

So the question is if Lyra handles ALL the failures (and so standard recovery should be turned off) or if Lyra provides just additional checks to the standard recovery mechanism (and so standard recovery should be turned on).

I'm asking because we encounter some strange behavior (basically recovery doesn't work) and maybe the problem is that we use Lyra and have recovery enabled on the `ConnectionFactory` at the same time.

Thanks!

**Comment by dimagol1989** [comment]
see #80

**Comment by michaelklishin** [comment]
Lyra and RabbitMQ Java client's recovery feature are **mutually exclusive** and **must not be used together**. See #82.
