### ISSUE TITLE
support withUri() in ConnectionOptions

### ISSUE THREAD

**Issue by neuhaus** [jhalterman/lyra#69]
Feature request:

The rabbitmq java client supports `factory.setUri()`, in order to switch to lyra I have to add quite a bit of extra code because it doesn't support URIs.

Please add support for URIs to ConnectionOptions

**Comment by jhalterman** [comment]
Care to send a pull request for this?

**Comment by neuhaus** [comment]
Given that getAdresses tries to use ConnectionOptions host value first and then falls back to factory.getHost this seems to be easy.

Actually I noticed that I will need `setURIs()` which is not so easy currently unless it is mandatory that only the host changes among the URIs, not the port, virtualhost etc.

**Comment by neuhaus** [comment]
Please let me know what you think. I will not actually use this, I will use `withHosts()` myself.

**Comment by neuhaus** [comment]
Added pull request #70

**Comment by jhalterman** [comment]
This looks good - thanks!
