### ISSUE TITLE
Moving to latest RabbitMQ Java Client 4.0

### ISSUE THREAD

**Issue by igreenfield** [jhalterman/lyra#71]
When you intend to move to the new client?

<dependency>
  <groupId>com.rabbitmq</groupId>
  <artifactId>amqp-client</artifactId>
  <version>4.0.0</version>
</dependency>

**Comment by michaelklishin** [comment]
The most recent version is `4.0.2` and `4.1.0` is not far off.

**Comment by igreenfield** [comment]
@michaelklishin I create pull request to move to latest java driver.

**Comment by igreenfield** [comment]
@jhalterman Hi would you merge #72 so we can benefit the NIO and the new stats?

**Comment by yairogen** [comment]
I too would like to use NIO

**Comment by michaelklishin** [comment]
#72 LGTM.
